# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identification', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('lmodel', models.CharField(max_length=100)),
                ('lcolor', models.CharField(max_length=100)),
            ],
        ),
    ]
