# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-08 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
