# Generated by Django 3.0.2 on 2020-01-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0005_laptop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='Image',
            field=models.ImageField(blank=True, upload_to='owner_image'),
        ),
    ]
