# Generated by Django 3.0.2 on 2020-01-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0006_laptop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='Image',
            field=models.ImageField(upload_to='owner_image'),
        ),
    ]
