# Generated by Django 3.0.2 on 2020-01-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0007_auto_20200111_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='Image',
        ),
        migrations.AddField(
            model_name='owner',
            name='image',
            field=models.ImageField(null=True, upload_to='owner_image'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
