# Generated by Django 3.0.2 on 2020-01-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0008_auto_20200113_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
