# Generated by Django 3.0.2 on 2020-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0009_laptop_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code_images'),
        ),
    ]
