# Generated by Django 2.1.3 on 2020-05-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0010_auto_20200113_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='occ',
            new_name='occupation',
        ),
    ]
