# Generated by Django 2.2.3 on 2020-05-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0011_auto_20200501_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_type',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher')], default='ST', max_length=2),
        ),
    ]
