# Generated by Django 2.2.3 on 2020-05-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0012_owner_owner_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_id',
            new_name='owner_id',
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_type',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('SA', 'Staff')], default='ST', max_length=2),
        ),
    ]
