# Generated by Django 2.2.3 on 2020-05-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0013_auto_20200510_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_first_name',
            new_name='owner_first_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='occupation',
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_last_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
