# Generated by Django 2.2.3 on 2020-05-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0014_auto_20200510_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_id',
            new_name='identification',
        ),
    ]
