# Generated by Django 2.2.3 on 2020-05-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0015_auto_20200510_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='identification',
            new_name='owner_id',
        ),
    ]
